# .github/workflows/deploy-frontend-dev.yml
name: Deploy Frontend (Dev)

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - 'backend/**'
      - 'terraform/**'
      - '.github/workflows/deploy-backend-dev.yml'
      - '.github/workflows/deploy-frontend-dev.yml'

jobs:
  deploy:
    name: Deploy Frontend to Firebase Hosting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ISHANCABPROJECT }}'
          projectId: ishancabproject
          channelId: live
